dataset:
  old_train_ratio: 0.8
  new_train_ratio: 0.8

training:
  batch_size: 64
  epochs_new: 10
  epochs_old: 5
  learning_rate: 0.001

logging:
  path: logs/
  level: info

output:
  output_path: results/


