# Datasets
train_ratio: 0.8
datasets: ["CIFAR10"]
split_indices: ["[0,4]", "[5,9]"]

# Model
model: "Resnet18"

# Training
batch_size: 64
epochs: 10
learning_rate: 0.001

# Logging
logging_path: ./logs/cifar10_resnet18
logging_level: INFO

# Results
exp_tag: "Cifar10 Resnet18 Experiment"

