# Datasets
train_ratio: 0.8
datasets: ["CIFAR10", "CIFAR100"]

# Model
model: "CNN"

# Training
batch_size: 64
epochs: 20
learning_rate: 0.001

# Logging
logging_path: ./logs/cifar_10_cifar100_CNN
logging_level: INFO

# Results
exp_tag: "Cifar10 Cifar100 CNN Experiment"

