# Datasets
train_ratio: 0.8
datasets: ["CIFAR100"]
split_indices: ["[0,9]", "[10,19]", "[20,29]"]

# Model
model: "Resnet18"

# Training
batch_size: 64
epochs: 20
learning_rate: 0.001

# Logging
logging_path: ./logs/cifar100_resnet18
logging_level: INFO

# Results
exp_tag: "Cifar100 resnet18 Experiment"

