# Datasets
train_ratio: 0.8
datasets: ["CIFAR100"]
split_indices: ["[0, 1, 2 , 3, 4, 5, 6, 7, 8, 9]", "[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]", "[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]"]

# Model
model: "resnet18"

# Training
batch_size: 64
epochs: 5
learning_rate: 0.001

# Logging
logging_path: ./logs/log
logging_level: INFO

# Results
exp_tag: "Cifar100 resnet18 Experiment"

