# Datasets
train_ratio: 0.8
datasets: ["CIFAR100"]
split_indices: ["[0,49]", "[50,99]"]

# Model
model: "CNN"

# Training
batch_size: 64
epochs: 20
learning_rate: 0.001

# Logging
logging_path: ./logs/cifar100_CNN
logging_level: INFO

# Results
exp_tag: "Cifar100 CNN Experiment"

