# Datasets
train_ratio: 0.8
datasets: ["CIFAR10"]
split_indices: ["[0,4]", "[5,9]"]

# Model
model: "CNN"

# Training
batch_size: 64
epochs: 20
learning_rate: 0.001

# Logging
logging_path: ./logs/cifar10_cnn
logging_level: INFO

# Results
exp_tag: "Cifar10 CNN Experiment"

