# Datasets
train_ratio: 0.8
datasets: ["MNIST"]
split_indices: ["[0,4]", "[5,9]"]

# Model
model: "CNN"

# Training
batch_size: 64
epochs: 3
learning_rate: 0.001

# Logging
logging_path: ./logs/default
logging_level: INFO

# Results
exp_tag: "Default Experiment"




