# Datasets
train_ratio: 0.8
datasets: ["MNIST"]
split_indices: ["[0, 1, 2, 3, 4]", "[5, 6, 7, 8, 9]"]

# Model
model: "CNN"

# Training
batch_size: 64
epochs: 3
learning_rate: 0.001

# Logging
logging_path: ./logs/default
logging_level: INFO

# Results
exp_tag: "Default Experiment"




