# Datasets
train_ratio: 0.8
datasets: ["MNIST", "FashionMNIST"]

# Model
model: "CNN"

# Training
batch_size: 64
epochs: 10
learning_rate: 0.001

# Logging
logging_path: ./logs/mnist_fashionmnist_cnn
logging_level: INFO

# Results
exp_tag: "MNIST FashionMNIST resnet18 Experiment"

