# Datasets
train_ratio: 0.8
datasets: ["MNIST", "FashionMNIST"]

# Model
model: "Resnet18"

# Training
batch_size: 64
epochs: 10
learning_rate: 0.001

# Logging
logging_path: ./logs/mnist_fashionmnist_resnet18
logging_level: INFO

# Results
exp_tag: "MNIST FashionMNIST Resnet18 Experiment"

